name       : enet
version    : 1.3.17
release    : 2
source     :
    - https://github.com/lsalzman/enet/archive/v1.3.17.tar.gz : 1e0b4bc0b7127a2d779dd7928f0b31830f5b3dcb7ec9588c5de70033e8d2434a
license    : MIT
component  : programming
summary    : Reliable UDP networking library
description: |
    ENet's purpose is to provide a relatively thin, simple and robust network communication layer on top of UDP (User Datagram Protocol).The primary feature it provides is optional reliable, in-order delivery of packets.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
